"""Taste calibration — measure user-vs-VLM agreement and derive trust zones.

Reads harness/memories/preferences.jsonl (votes recorded by request_keep),
computes per-aspect agreement rates with Wilson 95% confidence intervals, and
writes harness/memories/oracle-trust.md (the AUTO/ASK zone map the agent reads
before trusting pairwise verdicts).

Zone rules (TASTE-AND-LEARNING-ROADMAP.md rev 2, review fixes #2/#3):
  - AUTO requires N >= 10 votes AND lower Wilson bound >= 0.80
  - anything below: ASK (human verdict required)
  - motion is PROVISIONAL until native video input works (montage instrument)
  - also tracks both_bad rate per aspect (absolute-calibration signal)

Run:
    harness/.venv/Scripts/python.exe harness/calibrate.py
"""
from __future__ import annotations

import json
import math
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

MEMORIES = Path(__file__).parent / "memories"
PREFERENCES = MEMORIES / "preferences.jsonl"
FEEDBACK = MEMORIES / "feedback.jsonl"
TRUST = MEMORIES / "oracle-trust.md"


def wilson_interval(successes: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Wilson score interval for a binomial proportion."""
    if n == 0:
        return (0.0, 0.0)
    p = successes / n
    denom = 1 + z * z / n
    center = (p + z * z / (2 * n)) / denom
    margin = (z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))) / denom
    return (max(0.0, center - margin), min(1.0, center + margin))


def load_votes() -> list[dict]:
    votes = []
    if not PREFERENCES.exists():
        return votes
    for line in PREFERENCES.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
            if rec.get("user_verdict") in ("a", "b"):
                votes.append(rec)
        except json.JSONDecodeError:
            continue
    return votes


def load_feedback() -> list[dict]:
    notes = []
    if not FEEDBACK.exists():
        return notes
    for line in FEEDBACK.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            notes.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return notes


def main() -> None:
    votes = load_votes()
    feedback = load_feedback()

    # skip user-directed fixes: no VLM verdict to compare against
    comparable = [v for v in votes if not v.get("user_directed") and v.get("vlm_verdict")]

    if not votes:
        print("No votes recorded yet (preferences.jsonl is empty).")
        print("Votes accumulate automatically at every request_keep decision.")
        return

    # per-aspect agreement
    by_aspect: dict[str, dict] = defaultdict(lambda: {"n": 0, "agree": 0})
    for v in comparable:
        aspect = v.get("aspect") or "unspecified"
        user = v.get("user_verdict")
        vlm_says_b = "after" in str(v.get("vlm_verdict", "")).lower() or str(v.get("vlm_verdict", "")).strip().lower().endswith(("second", "b"))
        vlm = "b" if vlm_says_b else "a"
        by_aspect[aspect]["n"] += 1
        if user == vlm:
            by_aspect[aspect]["agree"] += 1

    lines = [
        "# Oracle Trust — AUTO/ASK zones for pairwise verdicts",
        "",
        f"> Generated by calibrate.py at {datetime.now().isoformat(timespec='seconds')}.",
        "> The agent reads this before trusting a pairwise verdict in AUTO mode.",
        "> AUTO = agent may keep winning verdicts without asking. ASK = every keep",
        "> decision goes through request_keep (which also generates calibration data).",
        "",
        "## Zones",
        "",
        "| Aspect | Votes | Agreement | Wilson 95% | Zone |",
        "|---|---|---|---|---|",
    ]
    zones: dict[str, str] = {}
    for aspect in sorted(by_aspect):
        d = by_aspect[aspect]
        n, agree = d["n"], d["agree"]
        rate = agree / n if n else 0.0
        lo, hi = wilson_interval(agree, n)
        zone = "AUTO" if (n >= 10 and lo >= 0.80) else "ASK"
        if aspect == "motion":
            zone = f"{zone} (PROVISIONAL — montage instrument; revisit with native video input)"
        zones[aspect] = zone
        lines.append(f"| {aspect} | {n} | {agree}/{n} ({rate:.0%}) | [{lo:.0%}, {hi:.0%}] | {zone} |")

    if not by_aspect:
        lines.append("| (no comparable votes yet — all user-directed or no VLM verdict) | | | | ASK |")

    # absolute-calibration signal: both_bad / rejected-with-note rate per aspect
    both_bad = defaultdict(int)
    for f in feedback:
        if f.get("verdict") == "rejected_with_note":
            both_bad[f.get("aspect") or "unspecified"] += 1

    lines += [
        "",
        "## Rules",
        "",
        "- AUTO requires N >= 10 votes AND lower Wilson bound >= 80%.",
        "- Recalibrate: every 20 cycles, on VLM model change, or when a spot check disagrees.",
        "- Every 5th AUTO decision still surfaces as a spot-check vote (keeps data flowing).",
        "- Never trust cross-call absolute scores; pairwise verdicts only.",
        "",
        "## Vote totals",
        "",
        f"- Total votes: {len(votes)} (comparable with VLM verdicts: {len(comparable)}; "
        f"user-directed: {len(votes) - len(comparable)})",
        f"- Feedback notes: {len(feedback)}",
    ]
    if both_bad:
        lines += ["", "## Rejection notes per aspect (absolute-level signal)", ""] + [
            f"- {k}: {v}" for k, v in sorted(both_bad.items())
        ]

    TRUST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nWritten to {TRUST}")


if __name__ == "__main__":
    main()
